// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Support.Infrastructure.Db;

#nullable disable

namespace Support.Infrastructure.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20251221222038_SeedDocumentRequests")]
    partial class SeedDocumentRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Support.Core.Entities.DocumentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DocumentRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 21, 21, 20, 38, 189, DateTimeKind.Utc).AddTicks(2400),
                            DocumentType = "Transcript of Records",
                            FacultyId = 1,
                            Status = "Pending",
                            UserId = "18001/2024"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 21, 19, 20, 38, 189, DateTimeKind.Utc).AddTicks(2408),
                            DocumentType = "Certificate of Enrollment",
                            FacultyId = 1,
                            Status = "Pending",
                            UserId = "19005/2023"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 21, 17, 20, 38, 189, DateTimeKind.Utc).AddTicks(2410),
                            DocumentType = "Diploma Supplement",
                            FacultyId = 2,
                            Status = "Pending",
                            UserId = "21045/2024"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 21, 10, 20, 38, 189, DateTimeKind.Utc).AddTicks(2411),
                            DocumentType = "Health Insurance Form",
                            FacultyId = 1,
                            Status = "Pending",
                            UserId = "18099/2022"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 20, 22, 20, 38, 189, DateTimeKind.Utc).AddTicks(2413),
                            DocumentType = "Tax Relief Certificate",
                            FacultyId = 1,
                            Status = "Pending",
                            UserId = "22011/2024"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 19, 22, 20, 38, 189, DateTimeKind.Utc).AddTicks(2416),
                            DocumentType = "Military Service Proof",
                            FacultyId = 2,
                            Status = "Pending",
                            UserId = "19033/2023"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 21, 22, 5, 38, 189, DateTimeKind.Utc).AddTicks(2417),
                            DocumentType = "Public Transport Discount",
                            FacultyId = 1,
                            Status = "Pending",
                            UserId = "20088/2024"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 21, 21, 50, 38, 189, DateTimeKind.Utc).AddTicks(2419),
                            DocumentType = "Student Visa Support",
                            FacultyId = 2,
                            Status = "Pending",
                            UserId = "25001/2024"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 21, 18, 20, 38, 189, DateTimeKind.Utc).AddTicks(2420),
                            DocumentType = "Erasmus Application Form",
                            FacultyId = 1,
                            Status = "Pending",
                            UserId = "24012/2024"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
