using System;
using System.Threading.Tasks;
using Identity.Application.DTO;
using Identity.Application.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

[ApiController]
[Route("api/identity")]
public class TwoFactorAuthController : ControllerBase
{
    private readonly ITwoFactorAuthService _svc;

    public TwoFactorAuthController(ITwoFactorAuthService svc)
    {
        _svc = svc;
    }

    /// <summary>
    /// Starts TOTP-based two-factor authentication (2FA) setup for a user.
    /// </summary>
    /// <remarks>
    /// The client must send the user's ID in the request body.
    ///
    /// Example request:
    ///
    ///     {
    ///         "userId": "e7c1bfc4-9d5a-4a0c-b621-1f0a4b7e31d3"
    ///     }
    ///
    /// Example successful response:
    ///
    ///     {
    ///         "success": true,
    ///         "message": "Two-factor authentication setup initialized.",
    ///         "manualEntryKey": "JBSWY3DPEHPK3PXP",
    ///         "qrCodeBase64": "data:image/png;base64,iVBORw0KGgo...",
    ///         "otpAuthUri": "otpauth://totp/StudentSystem:user@example.com?secret=JBSWY3DPEHPK3PXP&issuer=StudentSystem",
    ///         "error": "None"
    ///     }
    ///
    /// Example error response when the user cannot be found:
    ///
    ///     {
    ///         "success": false,
    ///         "message": "User not found.",
    ///         "manualEntryKey": null,
    ///         "qrCodeBase64": null,
    ///         "otpAuthUri": null,
    ///         "error": "UserNotFound"
    ///     }
    ///
    /// Note: this endpoint always returns HTTP 200. 
    /// Check the <c>success</c> and <c>error</c> fields in the response body
    /// to determine whether the operation completed successfully.
    /// </remarks>
    /// <response code="200">
    /// 2FA setup initialized. The response body contains details about success and error state.
    /// </response>
    [HttpPost("enable-2fa")]
    public async Task<IActionResult> Enable([FromBody] TwoFAConfirmRequest dto)
    {
        var res = await _svc.EnableTwoFactorAsync(dto.UserId);
        return Ok(res);
    }

    /// <summary>
    /// Confirms 2FA setup by validating the TOTP code entered by the user.
    /// </summary>
    /// <remarks>
    /// The user must provide the user ID and the TOTP code generated by an authenticator app.
    ///
    /// Example request:
    ///
    ///     {
    ///         "userId": "e7c1bfc4-9d5a-4a0c-b621-1f0a4b7e31d3",
    ///         "code": "123456"
    ///     }
    ///
    /// Example successful response:
    ///
    ///     {
    ///         "success": true,
    ///         "message": "Two-factor authentication has been enabled.",
    ///         "recoveryCodes": [
    ///             "39db-fa22-9c43",
    ///             "f832-bc18-23be",
    ///             "11ca-9b12-a3f1"
    ///         ],
    ///         "error": "None"
    ///     }
    ///
    /// Example invalid code (HTTP 401 Unauthorized):
    ///
    ///     {
    ///         "success": false,
    ///         "message": "The provided TOTP code is invalid.",
    ///         "recoveryCodes": null,
    ///         "error": "InvalidCode"
    ///     }
    ///
    /// Example rate limited (HTTP 429 Too Many Requests):
    ///
    ///     {
    ///         "success": false,
    ///         "message": "Too many failed attempts. Please wait before trying again.",
    ///         "recoveryCodes": null,
    ///         "error": "RateLimited"
    ///     }
    ///
    /// Possible values of the <c>error</c> field:
    /// - <c>None</c> – operation succeeded.
    /// - <c>InvalidCode</c> – TOTP code is invalid or expired.
    /// - <c>RateLimited</c> – too many failed attempts in a short period.
    /// - <c>UserNotFound</c> – user does not exist.
    /// - <c>NotInitialized</c> – 2FA setup has not been started for this user.
    /// </remarks>
    /// <response code="200">2FA successfully confirmed and enabled.</response>
    /// <response code="400">Invalid request or invalid user state (e.g. 2FA not initialized).</response>
    /// <response code="401">Invalid TOTP code.</response>
    /// <response code="404">User not found.</response>
    /// <response code="429">Too many failed attempts (rate limited).</response>
    [HttpPost("enable-2fa/confirm")]
    public async Task<IActionResult> VerifySetup([FromBody] TwoFAConfirmRequest dto)
    {
        var res = await _svc.VerifySetupAsync(dto.UserId, dto.Code);

        if (!res.Success)
        {
            return res.Error switch
            {
                TwoFAVerificationError.InvalidCode => Unauthorized(res),
                TwoFAVerificationError.RateLimited => StatusCode(StatusCodes.Status429TooManyRequests, res),
                TwoFAVerificationError.UserNotFound => NotFound(res),
                _ => BadRequest(res)
            };
        }

        return Ok(res);
    }

    /// <summary>
    /// Verifies a TOTP code during login for a user with 2FA enabled.
    /// </summary>
    /// <remarks>
    /// This endpoint is called after the user has provided valid username and password
    /// and the system has determined that 2FA is required.
    ///
    /// Example request:
    ///
    ///     {
    ///         "userId": "e7c1bfc4-9d5a-4a0c-b621-1f0a4b7e31d3",
    ///         "code": "123456"
    ///     }
    ///
    /// Example successful response:
    ///
    ///     {
    ///         "success": true,
    ///         "message": "Two-factor authentication verified.",
    ///         "recoveryCodes": null,
    ///         "error": "None"
    ///     }
    ///
    /// Example invalid or expired code (HTTP 401 Unauthorized):
    ///
    ///     {
    ///         "success": false,
    ///         "message": "The provided verification code is invalid or expired.",
    ///         "recoveryCodes": null,
    ///         "error": "InvalidCode"
    ///     }
    ///
    /// Example user not found (HTTP 404 Not Found):
    ///
    ///     {
    ///         "success": false,
    ///         "message": "User not found.",
    ///         "recoveryCodes": null,
    ///         "error": "UserNotFound"
    ///     }
    ///
    /// Possible values of the <c>error</c> field are the same as for the setup confirmation:
    /// <c>None</c>, <c>InvalidCode</c>, <c>RateLimited</c>, <c>UserNotFound</c>, <c>NotEnabled</c>.
    /// </remarks>
    /// <response code="200">2FA verified and the login flow can proceed (e.g. JWT is issued).</response>
    /// <response code="400">Invalid request or user state (2FA not enabled).</response>
    /// <response code="401">Invalid TOTP code.</response>
    /// <response code="404">User not found.</response>
    /// <response code="429">Too many failed attempts (rate limited).</response>
    [HttpPost("verify-2fa")]
    public async Task<IActionResult> VerifyLogin([FromBody] TwoFAConfirmRequest dto)
    {
        var res = await _svc.VerifyLoginAsync(dto.UserId, dto.Code);

        if (!res.Success)
        {
            return res.Error switch
            {
                TwoFAVerificationError.InvalidCode => Unauthorized(res),
                TwoFAVerificationError.RateLimited => StatusCode(StatusCodes.Status429TooManyRequests, res),
                TwoFAVerificationError.UserNotFound => NotFound(res),
                _ => BadRequest(res)
            };
        }

        return Ok(res);
    }
}
