// <auto-generated />
using System;
using Faculty.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faculty.Infrastructure.Migrations
{
    [DbContext(typeof(FacultyDbContext))]
    partial class FacultyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Faculty.Core.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Abbreviation = "FCS",
                            CreatedAt = new DateTime(2025, 11, 9, 0, 41, 8, 437, DateTimeKind.Utc).AddTicks(3057),
                            Description = "Leading technology and innovation education",
                            Name = "Faculty of Computer Science",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 0, 41, 8, 437, DateTimeKind.Utc).AddTicks(3057)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Abbreviation = "FENG",
                            CreatedAt = new DateTime(2025, 11, 9, 0, 41, 8, 437, DateTimeKind.Utc).AddTicks(3057),
                            Description = "Comprehensive engineering programs",
                            Name = "Faculty of Engineering",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 0, 41, 8, 437, DateTimeKind.Utc).AddTicks(3057)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Abbreviation = "FBUS",
                            CreatedAt = new DateTime(2025, 11, 9, 0, 41, 8, 437, DateTimeKind.Utc).AddTicks(3057),
                            Description = "Business administration and management",
                            Name = "Faculty of Business",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 9, 0, 41, 8, 437, DateTimeKind.Utc).AddTicks(3057)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
