using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Support.Infrastructure.Pdf;

public class StudentConfirmationPdf : IDocument
{
    private readonly StudentConfirmationData _data;

    public StudentConfirmationPdf(StudentConfirmationData data)
    {
        _data = data;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);
            page.DefaultTextStyle(x => x.FontSize(11));

            page.Header()
                .AlignCenter()
                .Text(_data.University)
                .FontSize(16)
                .SemiBold();

            page.Content().Column(column =>
            {
                column.Spacing(20);

                column.Item().AlignCenter()
                    .Text("STUDENT CONFIRMATION")
                    .FontSize(20)
                    .Bold();

                column.Item().LineHorizontal(1);

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.ConstantColumn(170);
                        columns.RelativeColumn();
                    });

                    Row(table, "Student:", _data.StudentName);
                    Row(table, "Index number:", _data.IndexNumber);
                    Row(table, "Faculty:", _data.Faculty);
                    Row(table, "Study program:", _data.StudyProgram);
                    Row(table, "Study cycle:", _data.StudyCycle);
                    Row(table, "Academic year:", _data.AcademicYear);
                });

                column.Item().PaddingTop(30)
                    .Text("This document confirms that the above-mentioned person is a regular student.")
                    .Italic();

                column.Item().PaddingTop(40).Row(row =>
                {
                    row.RelativeItem().Text($"Date: {_data.Date}");
                    row.RelativeItem().AlignRight().Text("Authorized signature");
                });
            });

            page.Footer()
                .AlignCenter()
                .Text("Generated by UNSA Student Management System")
                .FontSize(9)
                .FontColor(Colors.Grey.Medium);
        });
    }

    private static void Row(TableDescriptor table, string label, string value)
    {
        table.Cell().PaddingVertical(6).Text(label).SemiBold();
        table.Cell().PaddingVertical(6).Text(value);
    }
}
